# fly.toml app configuration file generated for rsshub-cy on 2023-05-09T21:06:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rsshub-cy"
primary_region = "hkg"

[http_service]
  internal_port = 1200
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
